"""Add NisanyanDemographics model

Revision ID: 3d9add235bd8
Revises: 1369ebc39da0
Create Date: 2026-05-20 16:19:29.572926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9add235bd8'
down_revision: Union[str, None] = '1369ebc39da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nisanyan_demographics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('settlement_name', sa.String(), nullable=False),
    sa.Column('historical_name', sa.String(), nullable=True),
    sa.Column('cultural_origin', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nisanyan_demographics'))
    )
    op.create_index(op.f('ix_nisanyan_demographics_district'), 'nisanyan_demographics', ['district'], unique=False)
    op.create_index(op.f('ix_nisanyan_demographics_province'), 'nisanyan_demographics', ['province'], unique=False)
    op.create_index('ix_nisanyan_province_district', 'nisanyan_demographics', ['province', 'district'], unique=False)
    op.create_index('ix_nisanyan_settlement', 'nisanyan_demographics', ['settlement_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nisanyan_settlement', table_name='nisanyan_demographics')
    op.drop_index('ix_nisanyan_province_district', table_name='nisanyan_demographics')
    op.drop_index(op.f('ix_nisanyan_demographics_province'), table_name='nisanyan_demographics')
    op.drop_index(op.f('ix_nisanyan_demographics_district'), table_name='nisanyan_demographics')
    op.drop_table('nisanyan_demographics')
    # ### end Alembic commands ###
