"""Add IntelligenceSource model

Revision ID: a528e8735b40
Revises: a9c0d1e2f3a4
Create Date: 2026-05-18 03:04:37.785301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a528e8735b40'
down_revision: Union[str, None] = 'a9c0d1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_fetched_at')
    # ### end Alembic commands ###
