"""Add vector embedding table

Revision ID: e643666efc98
Revises: d4e5f6a7b8c9
Create Date: 2026-05-16 01:39:37.289768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = 'e643666efc98'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_analyses'))
    )
    op.create_index(op.f('ix_region_analyses_district'), 'region_analyses', ['district'], unique=False)
    op.create_index(op.f('ix_region_analyses_neighborhood'), 'region_analyses', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_region_analyses_province'), 'region_analyses', ['province'], unique=False)
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    op.create_table('content_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('embedding', VECTOR(768), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_content_embeddings_content_id_contents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_embeddings')),
    sa.UniqueConstraint('content_id', name='uq_content_embeddings_content_id')
    )
    op.alter_column('complaints_radar_cache', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('content_labels', sa.Column('crisis_score', sa.Integer(), nullable=True))
    op.add_column('content_labels', sa.Column('sentiment', sa.String(), nullable=True))
    op.alter_column('contents', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('contents', 'is_analyzed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_contents_is_analyzed'), 'contents', ['is_analyzed'], unique=False)
    op.create_index(op.f('ix_election_demographic_stats_bucket'), 'election_demographic_stats', ['bucket'], unique=False)
    op.create_index(op.f('ix_election_demographic_stats_dimension'), 'election_demographic_stats', ['dimension'], unique=False)
    op.create_index(op.f('ix_election_demographic_stats_district'), 'election_demographic_stats', ['district'], unique=False)
    op.create_index(op.f('ix_election_demographic_stats_election_detail'), 'election_demographic_stats', ['election_detail'], unique=False)
    op.create_index(op.f('ix_election_demographic_stats_party'), 'election_demographic_stats', ['party'], unique=False)
    op.create_index(op.f('ix_election_region_archives_district_key'), 'election_region_archives', ['district_key'], unique=False)
    op.create_index(op.f('ix_election_region_trends_district'), 'election_region_trends', ['district'], unique=False)
    op.create_index(op.f('ix_election_region_trends_party'), 'election_region_trends', ['party'], unique=False)
    op.create_index(op.f('ix_election_region_trends_source_json_file'), 'election_region_trends', ['source_json_file'], unique=False)
    op.add_column('sources', sa.Column('domain', sa.String(), nullable=True))
    op.alter_column('sources', 'type',
               existing_type=postgresql.ENUM('rss', 'youtube', 'x', name='sourcetype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('rss', 'youtube', 'x', name='sourcetype'),
               existing_nullable=False)
    op.drop_column('sources', 'domain')
    op.drop_index(op.f('ix_election_region_trends_source_json_file'), table_name='election_region_trends')
    op.drop_index(op.f('ix_election_region_trends_party'), table_name='election_region_trends')
    op.drop_index(op.f('ix_election_region_trends_district'), table_name='election_region_trends')
    op.drop_index(op.f('ix_election_region_archives_district_key'), table_name='election_region_archives')
    op.drop_index(op.f('ix_election_demographic_stats_party'), table_name='election_demographic_stats')
    op.drop_index(op.f('ix_election_demographic_stats_election_detail'), table_name='election_demographic_stats')
    op.drop_index(op.f('ix_election_demographic_stats_district'), table_name='election_demographic_stats')
    op.drop_index(op.f('ix_election_demographic_stats_dimension'), table_name='election_demographic_stats')
    op.drop_index(op.f('ix_election_demographic_stats_bucket'), table_name='election_demographic_stats')
    op.drop_index(op.f('ix_contents_is_analyzed'), table_name='contents')
    op.alter_column('contents', 'is_analyzed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contents', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.drop_column('content_labels', 'sentiment')
    op.drop_column('content_labels', 'crisis_score')
    op.alter_column('complaints_radar_cache', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_table('content_embeddings')
    op.drop_index(op.f('ix_region_analyses_province'), table_name='region_analyses')
    op.drop_index(op.f('ix_region_analyses_neighborhood'), table_name='region_analyses')
    op.drop_index(op.f('ix_region_analyses_district'), table_name='region_analyses')
    op.drop_table('region_analyses')
    # ### end Alembic commands ###
