"""Add OSINT features and indices

Revision ID: fe3aabf62742
Revises: f70be04f5465
Create Date: 2026-05-10 14:48:18.221814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3aabf62742'
down_revision: Union[str, None] = 'f70be04f5465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('person', 'organization', 'location', 'event', name='entitytype'), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('name', name=op.f('uq_entities_name'))
    )
    op.create_index('ix_entities_name', 'entities', ['name'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('term', name=op.f('uq_keywords_term'))
    )
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('alias_term', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_aliases_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases'))
    )
    op.create_index('ix_aliases_alias_term', 'aliases', ['alias_term'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_entity_relations_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_entity_relations_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_entity_relations_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relations'))
    )
    op.add_column('content_labels', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('content_labels', sa.Column('manipulation_prob', sa.Float(), nullable=True))
    op.add_column('content_labels', sa.Column('bot_likelihood', sa.Float(), nullable=True))
    op.add_column('content_labels', sa.Column('sarcasm_detected', sa.Boolean(), nullable=True))
    op.create_index('ix_content_metrics_captured_at', 'content_metrics', ['captured_at'], unique=False)
    # Sıfır DB'de kısıt adı farklı olabilir veya yoktur; drop_constraint migration'ı düşürürdü.
    # op.drop_constraint('contents_external_id_key', 'contents', type_='unique')
    # f70'te domain / is_analyzed yok; indekslerden önce eklenmeli
    op.add_column('contents', sa.Column('domain', sa.String(), nullable=False, server_default='general'))
    op.add_column('contents', sa.Column('is_analyzed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index('ix_contents_domain', 'contents', ['domain'], unique=False)
    op.create_index('ix_contents_platform_published', 'contents', ['platform', 'published_at'], unique=False)
    # external_id üzerinde unique zaten f70'te var; tekrar eklemek duplicate constraint hatası verir.
    # op.create_unique_constraint(op.f('uq_contents_external_id'), 'contents', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_contents_external_id'), 'contents', type_='unique')
    op.drop_index('ix_contents_platform_published', table_name='contents')
    op.drop_index('ix_contents_domain', table_name='contents')
    op.drop_column('contents', 'is_analyzed')
    op.drop_column('contents', 'domain')
    # op.create_unique_constraint('contents_external_id_key', 'contents', ['external_id'])
    op.drop_index('ix_content_metrics_captured_at', table_name='content_metrics')
    op.drop_column('content_labels', 'sarcasm_detected')
    op.drop_column('content_labels', 'bot_likelihood')
    op.drop_column('content_labels', 'manipulation_prob')
    op.drop_column('content_labels', 'sentiment_score')
    op.drop_table('entity_relations')
    op.drop_index('ix_aliases_alias_term', table_name='aliases')
    op.drop_table('aliases')
    op.drop_table('keywords')
    op.drop_index('ix_entities_name', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
